---
- name: install
  tags:
    - redis
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: "{{ item.package }}"
        derivation: "{{ item.derivation }}"
      loop:
        - { package: redis, derivation: redis }
        - { package: iredis, derivation: iredis }
