---
- name: install
  tags:
    - cht.sh
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: cht-sh
        derivation: cht.sh

- name: symlink config
  tags:
    - cht.sh
    - link
    - cli
  block:
    - name: create config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/cht.sh"
        state: directory

    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/cht.sh/"
        dest: "{{ ansible_env.HOME }}/.config/cht.sh"
        state: link
        force: yes
