---
- name: symlink bashrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/bash/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link
    force: yes
  tags:
    - shell
    - link
    - cli

- name: symlink zshrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes
  tags:
    - shell
    - link
    - cli

- name: symlink aliases
  ansible.builtin.file:
    src: "{{ role_path }}/files/shell/.aliases"
    dest: "{{ ansible_env.HOME }}/.aliases"
    state: link
    force: yes
  tags:
    - shell
    - link
    - cli
