---
- name: install
  tags:
    - nodejs
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: "{{ item.package }}"
        derivation: "{{ item.derivation }}"
      loop:
        - { package: nodejs, derivation: nodejs }
        - { package: typescript, derivation: typescript }
