---
- name: install
  tags:
    - python
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: pipx
        derivation: pipx
