---
- name: install
  tags:
    - mysql
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: "{{ item.package }}"
        derivation: "{{ item.derivation }}"
      loop:
        - { package: mysql, derivation: mariadb-server }
        - { package: mycli, derivation: mycli }

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/mycli/.myclirc"
    dest: ~/.myclirc
    state: link
  tags:
    - github
    - link
    - cli
