---
- name: check if installed
  ansible.builtin.command: google-chrome --version
  register: chrome_version
  ignore_errors: yes
  changed_when: false

- name: download installer
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "{{ tmp_dir }}/google-chrome-stable_current_amd64.deb"
  when: chrome_version.rc != 0

- name: install
  ansible.builtin.apt:
    deb: "{{ tmp_dir }}/google-chrome-stable_current_amd64.deb"
  when: chrome_version.rc != 0
  become: true
