---
- name: install
  tags:
    - go
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: go
        derivation: go
