---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - alacritty

- name: alacritty | create config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
  tags:
    - alacritty
    - link
    - desktop

- name: alacritty | symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty"
    dest: "{{ ansible_env.HOME }}/.config/alacritty"
    state: link
    force: yes
  tags:
    - alacritty
    - link
    - desktop

- name: wezterm | symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/wezterm/.wezterm.lua"
    dest: "{{ ansible_env.HOME }}/.wezterm.lua"
    state: link
    force: yes
  tags:
    - wezterm
    - link
    - desktop

- name: kitty | symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/kitty"
    dest: "{{ ansible_env.HOME }}/.config/kitty"
    state: link
    force: yes
  tags:
    - kitty
    - link
    - desktop
