---
- name: install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true

- name: check docker version
  command: "docker --version"
  register: docker_version
  ignore_errors: yes
  changed_when: false

- name: add official GPG key for ubuntu
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true
  when: ansible_distribution != 'Debian' and docker_version.rc != 0

- name: add official GPG key for debian
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true
  when: ansible_distribution == 'Debian' and docker_version.rc != 0


- name: get system architecture
  ansible.builtin.command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: add docker stable ubuntu repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    mode: "0644"
  become: true
  when: ansible_distribution != 'Debian' and docker_version.rc != 0

- name: add docker stable debian repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    mode: "0644"
  become: true
  when: ansible_distribution == 'Debian' and docker_version.rc != 0

- name: install docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  when: docker_version.rc != 0

- name: enable and start docker service
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  become: true
  when: docker_version.rc != 0

- name: add user to docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true
  when: docker_version.rc != 0
