---
- name: install
  tags:
    - starship
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: starship
        derivation: starship

- name: symlink config
  tags:
    - tmux
    - link
    - cli
  block:
    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/starship/starship.toml"
        dest: ~/.config/starship.toml
        state: link
