---
- name: install
  tags:
    - php
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: "{{ item.package }}"
        derivation: "{{ item.derivation }}"
      loop:
        - { package: php82, derivation: php-with-extensions }
        - { package: php82Packages.composer, derivation: composer }

- name: phpactor | symlink config
  tags:
    - php
    - link
    - cli
  block:
    - name: phpactor | create config directory
      ansible.builtin.file:
        path: ~/.config/phpactor
        state: directory

    - name: phpactor | symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/phpactor"
        dest: ~/.config/phpactor
        state: link
        force: yes
