---
- name: install
  tags:
    - neovim
    - install
    - cli
  block:
    - name: install
      include_tasks: roles/nix/tasks/install_package.yml
      vars:
        package: neovim
        derivation: neovim

- name: symlink config
  tags:
    - neovim
    - link
    - cli
  block:
    - name: create config directory
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory

    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/nvim"
        dest: ~/.config/nvim
        state: link
        force: yes
