---
- name: install
  tags:
    - fonts
    - install
    - desktop
  block:
  - name: create directory
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.fonts/zip"
      state: directory

  - name: download hack font
    ansible.builtin.get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
      dest: "{{ ansible_env.HOME }}/.fonts/zip/Hack.zip"

  - name: unarchive hack font
    ansible.builtin.unarchive:
      src: "{{ ansible_env.HOME }}/.fonts/zip/Hack.zip"
      dest: "{{ ansible_env.HOME }}/.fonts"
